### PR TITLE
Gen a .pc file. Inst dir overrides. Support GNUInstallDirs. Fix inst paths.

### PR DESCRIPTION
**Pull request by terminator356**
Awesome library, thanks so much for this real hidden gem!
I wish you success with it. It works for me.

Here's my contribution if you like. May want to edit for content or variable naming.

Generate a pkgconfig *.pc file.
Allow installation directory overrides and support CMake GNUInstallDirs.
Fixup most installation paths **except** the docs. I left that part alone since I didn't generate any here.

Wish / possible future work: More login auth types?

### CODE REVIEW

**Comment by karastojko** [comment]
Thank you for the PR. Let me test it and will let you know about the merge.
I was thinking about more authentication types, but before that I would like to add asynchronous counterparts of I/O operations, few more IMAP and MIME features.

**Comment by terminator356** [comment]
I've been a busy beaver. See the branch 'tim_1' of my fork of mailio, on my github page.
`
- Fix exception on lower case letters: "Bad hexadecimal digit" in quoted_printable::decode().
   Convert the two characters to uppercase before checking.
 - Complete mailbox_stat_t statistics: messages_recent, messages_first_unseen,
    uidnext, uidvalidity. This REALLY helps with client message caching.
 - Add several new commands in imap.hpp, several do not select() first, for speed:
    mailbox_stat_t select_mailbox(): Exposes the protected select().
    mailbox_stat_t examine_mailbox(): Examine a mailbox.
    void fetch_message(): Has 'is_uid' parameter meaning 'message_no' param is a uid.
    void remove_message(): Has 'is_uid' parameter meaning 'message_no' param is a uid.
    void search_messages(): Has 'want_uids' parameter meaning return uids.
 - Add a new line_len_policy_t value: VERYLARGE = 16384. Required for certain received messages.
 - Add a separate '_decoder_line_policy' besides '_line_policy' to all objects.
   This allows a separate very large decoding policy while keeping a standard encoding policy.
`

The code is dirty at the moment, with my personal 'REMOVE Tim' bread-crumb markers
 and comments to be cleaned up.
However I'm happy to report that the library in its current state, even without async support,
 is not too shabby. I currently have a working client that implements caching (!)
 using the functionality that I added - the message uid and uidvalidity values especially help.
But it is quite slow in downloading all the messages.
I'm currently looking at ways to speed things up (barring async support).
Especially the fetch command, I'd like to add ranges to it instead of just a single message.
I'm also reading "IMAP4 Implementation Recommendations" RFC 2683 for some great tips.

A few notes:
I was in the process of adding checks, in most responses, that the command word is
 in fact found in the response, such as finding 'FETCH' in the response of a fetch command.
But in fetch_message() we have a curious situation in which, unlike the other commands,
 the response contains four parts instead of three, and the third is FETCH.
 this response has four parts and the third is FETCH,
 but tag_result_response is a tuple and there are only three items,
 and all of the library code wants to parse starting at the third item.
So in this case only, we are including the word FETCH in the parse,
 which the code below deems harmless because the FETCH is just a string atom
 and the code below just looks for the LIST token.
Nonetheless, the word FETCH will be the first atom returned in the mandatory list.
We could look for the word there. But then for consistency we should change
 all the other code to do the same (that is, include the response word).

I may need to add a feature which turns off exceptions in favour of return values,
 because Qt is telling me I must not 'throw' from inside a signal/slot handler
 in my worker QThread :-(

I hope all of this in not too overwhelming.
I just had to roll up my sleeves and dig in to the library.
Thanks.

**Comment by karastojko** [comment]
Thanks for the nice overview. I will go through the list of changes of your repository and one more user and cherry pick the features to merge with the master. Also I'll list you as contributor in the readme file. There are also semi-automated unit tests which are not published, so usually I write few tests when a new feature is added. Please be patient until I finish all of that since this is not my main job.

**Comment by terminator356** [comment]
Hi just a heads up: I submitted a new pull request replaces this one.
The new request is **not** incremental to this one.
It's my full, cleaned up fork of mailio. With a demo picture and info, too.
So if you'd like to grab it, then please ignore this request.
Thanks.

**Pull request merged**
