### PR TITLE
Replace format(string, bool) with format(string, message_format_options). Add add_bcc_headers opt

### PR DESCRIPTION
**Pull request by LhKipp**
Hi Tomislav,

opening this PR as a follow up to #150. Let me know what you think 👍🏻

### CODE REVIEW

**Comment by LhKipp** [comment]
FYI: The following testcases fail for me locally:
1. format_html_att
2. format_msg_att
3. format_attachment_utf8
(They also fail on the master branch. So they are unrelated to this PR)

**Comment by karastojko** [comment]
Hey @LhKipp , thanks for the PR. I am taking a look now, and I will run these public tests and some private ones.

**Comment by karastojko** [comment]
Thanks for the PR, this is the right way to enhance message formatting.

**Comment by karastojko** [comment]
> FYI: The following testcases fail for me locally:
> 
>     1. format_html_att
>     2. format_msg_att
>     3. format_attachment_utf8
> 
> (They also fail on the master branch. So they are unrelated to this PR)
> 
> (Edit: Fixed formatting to make clear, that all 3 testcases fail locally on this branch and on the master branch for me)

The tests require two files `aleph0.png` and `cv.txt` for some cases. They should be installed when building with the `make install` (Unix) or from the solution when building the `install` project (Msvc/Windows). I will clarify that in the instructions, thanks for pointing this out.

**Pull request merged**
