### PR TITLE
Fix: Mentioned default in the readme differs from the default in CMakeLists.txt

### PR DESCRIPTION
**Pull request by LhKipp**
The default for `MAILIO_BUILD_SHARED_LIBRARY` is ON. However the readme says it is off.

I've only adapted the english readme, as I don't speak chinese. The same misalignment might exist in README_zh.md.

### CODE REVIEW

**Comment by tsurumi-yizhou** [comment]
I would translate the doc. However, I guess the default value may be ON?

**Comment by karastojko** [comment]
The default value is ON, but it can be set to OFF from the command line or by editing the Cmake file. Please add the change in the Chinese version, then I could merge the PR.

**Comment by LhKipp** [comment]
May I allow myself to expand the scope of this MR by the last 2 commits pushed? ( 15df8954617af23d0c44aa46754431d9f59adf13 and 5ab82273fa176564406c46c512d25c1cf144ec13).

CMake has a [default option](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) to decide whether a static or shared library shall be build. I've tested, that the new cmake file works as expected by executing the following commands:

```
mkdir build && cd build
cmake .. -DBUILD_SHARED_LIBS=ON && make
# A shared lib is build

cd .. && rm -r build
mkdir build && cd build
cmake .. -DBUILD_SHARED_LIBS=OFF && make
# A static lib is build

cd .. && rm -r build
mkdir build && cd build
cmake .. && make
# A shared lib is build
```

Additionally I've removed unit_test_framework from the link interface of the mailio library and added it to the tests. Currently users need to have unit_test_framework installed when linking with mailio (as mailio links it). Now users don't.

**Comment by tsurumi-yizhou** [comment]
> May I allow myself to expand the scope of this MR by the last 2 commits pushed? ( [15df895](https://github.com/karastojko/mailio/commit/15df8954617af23d0c44aa46754431d9f59adf13) and [5ab8227](https://github.com/karastojko/mailio/commit/5ab82273fa176564406c46c512d25c1cf144ec13)).
> 
> CMake has a [default option](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) to decide whether a static or shared library shall be build. In the first commit I remove the mailio specific option and use the standard one. I've tested, that the new cmake file works as expected by executing the following commands:
> 
> ```
> mkdir build && cd build
> cmake .. -DBUILD_SHARED_LIBS=ON && make
> # A shared lib is build
> 
> cd .. && rm -r build
> mkdir build && cd build
> cmake .. -DBUILD_SHARED_LIBS=OFF && make
> # A static lib is build
> 
> cd .. && rm -r build
> mkdir build && cd build
> cmake .. && make
> # A shared lib is build
> ```
> 
> Additionally I've removed unit_test_framework from the link interface of the mailio library and added it to the tests. Currently users need to have unit_test_framework installed when linking with mailio (as mailio links it). Now users don't.
> 
> If this MR is accepted as is, @tsurumi-yizhou could you please provide me a patch for the chinese readme (or could you follow up with another MR)? Thanks 👍🏻

The patch has pr to your fork branch.

**Comment by LhKipp** [comment]
@tsurumi-yizhou Thanks for providing a patch for the chinese readme. I've merged it into this MR and renamed the option name to reflect the option name change from this PR (`MAILIO_BUILD_SHARED_LIBRARY`->`BUILD_SHARED_LIBS`).

**Comment by LhKipp** [comment]
@karastojko Can you please take a look at this PR (relevant comment explaining what I've done, since you looked at it the first time: https://github.com/karastojko/mailio/pull/128#issuecomment-1590630666. Additionally I've changed the chinese README as requested).

**Comment by karastojko** [comment]
I will. Sorry for the delay, I was trying to finish the Vcpkg setup PR. It has also introduced changes to the `CMakeLists.txt`, thus I've tried to keep all the other changes to minimum.

**Comment by LhKipp** [comment]
Ah okay. I thought this PR has become forgotten. 

Feel free to finish the work on the vcpkg-pr first. I can rebase this branch.

**Comment by karastojko** [comment]
@LhKipp I have added you to the contributor list in the Readme file.
@tsurumi-yizhou Can you please add the same to the Chinese version from this [commit](https://github.com/karastojko/mailio/commit/75db981761cdc1fbf47a48f2f8f45fa283ed3781)?

**Pull request merged**
